/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String arrow = "assets/images/arrow.png";
  static const String Cata4 = "assets/images/Cata 4.png";
  static const String email = "assets/images/email.png";
  static const String forgetPass1 = "assets/images/forgetPass1.png";
  static const String forgetPass2 = "assets/images/forgetPass2.png";
  static const String jannah = "assets/fonts/jannah.ttf";
  static const String logo = "assets/images/logo.png";
  static const String onBoarding1 = "assets/images/onBoarding1.png";
  static const String onBoarding2 = "assets/images/onBoarding2.png";
  static const String onBoarding3 = "assets/images/onBoarding3.png";
  static const String resetPassword = "assets/images/resetPassword.png";
  static const String selectType = "assets/images/selectType.png";
  static const String splash = "assets/images/splash.png";
}
