/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String arrow = "assets/images/arrow.png";
  static const String Cata4 = "assets/images/Cata 4.png";
  static const String email = "assets/images/email.png";
  static const String forgetPass1 = "assets/images/forgetPass1.png";
  static const String forgetPass2 = "assets/images/forgetPass2.png";
  static const String jannah = "assets/fonts/jannah.ttf";
  static const String logo = "assets/images/logo.png";
  static const String onBoarding1 = "assets/images/onboarding1.png";
  static const String onBoarding2 = "assets/images/onboarding2.png";
  static const String onBoarding3 = "assets/images/onboarding3.png";
  static const String resetPassword = "assets/images/resetPassword.png";
  static const String selectType = "assets/images/choice_screen.png";
  static const String splash = "assets/images/Vector 16.png";
  static const String showPass = "assets/images/iconoir_eye-alt.png";
  static const String hidePass = "assets/images/ph_eye-closed-thin.png";
  static const String gifAnimation = "Gooey loader 1.gif";
  static const String profSettings = "assets/images/profile_settings.png";
  static const String secSettings = "assets/images/security.png";
  static const String notificationSettings = "assets/images/notification.png";
  static const String updateSettings = "assets/images/update.png";
  static const String logoutSettings = "assets/images/logout.png";
  static const String homeNavBar = "assets/images/homeNavBar.png";
  static const String settingNavBar = "assets/images/settingNavBar.png";
  static const String scanNavBar = "assets/images/scanNavBar.png";
  static const String profileNavBar = "assets/images/profileNavBar.png";
  static const String vectorNavBar = "assets/images/Vector13.png";
  static const String qrNotFound = "assets/images/qrNotFound.png";
}
